# Generated by Django 3.2.18 on 2023-02-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    """Makes `date_of_birth` accept null."""

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
