# Generated by Django 3.2.18 on 2023-03-25 19:22

import datetime as dt

from django.db import migrations, models


class Migration(migrations.Migration):
    """Generated by Django 3.2.18 on 2023-03-25 19:22."""

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=dt.datetime(2020, 5, 17, 0, 0)),
            preserve_default=False,
        ),
    ]
